### ISSUE TITLE
Cannot read property 'debug' of undefined

### ISSUE THREAD

**Issue by maktouch** [rudderlabs/rudder-sdk-node#61]
Rudderstack is filling Redis at a crazy rate. Looking at the bull jobs, it seems like they're failing 

```
Cannot read property 'debug' of undefined
```

Here's the stack trace: 

```
[
  "TypeError: Cannot read property 'debug' of undefined
      at Queue.<anonymous> (/app/node_modules/@rudderstack/rudder-sdk-node/index.js:115:21)
      at Queue.emit (events.js:315:20)
      at Queue.EventEmitter.emit (domain.js:467:12)
      at /app/node_modules/bull/lib/queue.js:1083:12
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)"
]
```

This is how I'm initializing Rudderstack

```lang=typescript
export function createRudderstackConnection(config: RudderstackConfig) {
  const client = new Analytics(config.rudderstack.write_key, `${config.rudderstack.data_plane_uri}/v1/batch`, {
    flushAt: 20,
    flushInterval: 20000,
    maxInternalQueueSize: 20000,
  });

  const redisOpts = parseRedisUrl(config.redis.connection);

  client.createPersistenceQueue(
    {
      redisOpts,
      prefix: 'rudder',
      isMultiProcessor: true,
      jobOpts: {
        maxAttempts: 3,
      },
    },
    console.error
  );

  return client;
}
```

**Comment by MoumitaM** [comment]
Hi @maktouch, 

Apologies for such a delayed response. The way you are Initializing looks fine to me. Can you double-check the data-plane URL and the Redis connection and then use a queueName(not the default one) while initialization. Like  below: 

```
client.createPersistenceQueue(
    {
      queueName: "pQueue",
      redisOpts,
      prefix: 'rudder',
      isMultiProcessor: true,
      jobOpts: {
        maxAttempts: 3,
      },
    },
    console.error
  );
  return client;
} 

```

**Comment by MoumitaM** [comment]
May I know which version of the SDK are you using?

**Comment by maktouch** [comment]
> May I know which version of the SDK are you using?

@rudderstack/rudder-sdk-node@1.0.14

I see that 1.1.1 is out, I'll upgrade and will report if it does the same thing.

**Comment by MoumitaM** [comment]
Kindly delete the node_modules and do a fresh npm install.
